---
name: "Deploy app to server"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: "Build and deploy app"
    runs-on: self-hosted

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/baonq243/cowbot:latest
      - name: run docker
        env:
          TOKEN: ${{ secrets.TOKEN }}
          LIST_ALLOW: ${{ secrets.LIST_ALLOW }}
          LIST_ADMIN: ${{ secrets.LIST_ADMIN }}
        run: |
          docker-compose down
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d
